name: Build and Publish Flatpak

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  release:
    types: [published]

env:
  FLATPAK_ID: org.hedgewars.Hedgewars64

jobs:
  build:
    runs-on: ${{ matrix.arch == 'aarch64' && 'ubuntu-24.04-arm' || 'ubuntu-latest' }}
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:gnome-48
      options: --privileged

    strategy:
      matrix:
        arch: [x86_64, aarch64]
      fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build Flatpak
        uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          bundle: ${{ env.FLATPAK_ID }}.flatpak
          manifest-path: ${{ env.FLATPAK_ID }}.yaml
          cache-key: flatpak-builder-${{ matrix.arch }}-${{ github.sha }}
          arch: ${{ matrix.arch }}
          upload-artifact: true

  publish-github-release:
    runs-on: ubuntu-latest
    needs: [build]
    if: github.event_name == 'release' && github.event.action == 'published'

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4

      - name: List downloaded files (for debugging)
        run: |
          echo "Downloaded files:"
          find . -name "*.flatpak" -type f
          ls -la

      - name: Upload x86_64 flatpak to GitHub Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ env.FLATPAK_ID }}-x86_64.flatpak/${{ env.FLATPAK_ID }}.flatpak
          asset_name: ${{ env.FLATPAK_ID }}-x86_64.flatpak
          asset_content_type: application/octet-stream

      - name: Upload aarch64 flatpak to GitHub Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ env.FLATPAK_ID }}-aarch64.flatpak/${{ env.FLATPAK_ID }}.flatpak
          asset_name: ${{ env.FLATPAK_ID }}-aarch64.flatpak
          asset_content_type: application/octet-stream
