name: Build and Publish Flatpak

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  release:
    types: [published]

env:
  FLATPAK_ID: org.hedgewars.Hedgewars64

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:gnome-48
      options: --privileged

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build Flatpak
        uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          bundle: ${{ env.FLATPAK_ID }}.flatpak
          manifest-path: ${{ env.FLATPAK_ID }}.yaml
          cache-key: flatpak-builder-${{ github.sha }}
          upload-artifact: true

  publish-github-release:
    runs-on: ubuntu-latest
    needs: [build]
    if: github.event_name == 'release' && github.event.action == 'published'

    steps:
      - name: Download built flatpak
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.FLATPAK_ID }}

      - name: Upload to GitHub Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ env.FLATPAK_ID }}.flatpak
          asset_name: ${{ env.FLATPAK_ID }}.flatpak
          asset_content_type: application/octet-stream
